import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const Header = require('../components/ui/Header').default;
  const Footer = require('../components/ui/Footer').default;

  return (
    <html lang="en">
      <body className={`${outfit.variable} font-outfit antialiased bg-[#0a0f0a]`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
